### ISSUE TITLE
能否可以增加手动修改v2ray.main.json的功能

### ISSUE THREAD

**Issue by lyx32** [kuoruan/openwrt-v2ray#107]
我的网件wndr4300 路由器，
刷的明月openwrt固件（lede17.0.1），
经过我多次测试发现，开启透明代理，并且添加防火墙入站规则之后
我浏览器就登录不了路由器（路由器ip192.168.10.1），显示服务器拒绝了我的连接
但是用ssh又可以正常登录，此时，我想修改v2ray.main.json则必须要将路由器恢复出厂设置，并全部重新设置。

**Comment by kuoruan** [comment]
```
/etc/init.d/v2ray stop
```
关闭服务即可

已提供自定义配置文件功能，不准备再添加手动修改功能。

**Comment by xspeed1989** [comment]
@kuoruan 大佬，自定义配置文件的功能没在luci上找到呢
