### ISSUE TITLE
自从4.28版本以后,编译都报错

### ISSUE THREAD

**Issue by TerryWang159** [kuoruan/openwrt-v2ray#108]
使用Openwrt 官方最新源文件 编译 v2ray-core 

自从4.28版本以后 ,没有一次编译通过的 .  都是出现同样的编译错误 ,代码滚回4.28-1后编译就过了 . 

Makefile:350: recipe for target '/home/terry/openwrt/build_dir/target-x86_64_musl/v2ray-core-full/v2ray-core-4.31.3/.built' failed
make[3]: *** [/home/terry/openwrt/build_dir/target-x86_64_musl/v2ray-core-full/v2ray-core-4.31.3/.built] Error 2
make[3]: Leaving directory '/home/terry/openwrt/package/v2ray-core'
time: package/v2ray-core/full/compile#67.46#20.27#24.81
package/Makefile:111: recipe for target 'package/v2ray-core/compile' failed
make[2]: *** [package/v2ray-core/compile] Error 2
make[2]: Leaving directory '/home/terry/openwrt'
package/Makefile:107: recipe for target '/home/terry/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/terry/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/terry/openwrt'
/home/terry/openwrt/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by kuoruan** [comment]
4.28版本以后需要 golang 15, 需要用最新的 SDK
但是当前最新的 SDK 有问题
