### ISSUE TITLE
请问如何降低 System Log 中 v2ray 的 log level？

### ISSUE THREAD

**Issue by h2fishcake** [kuoruan/openwrt-v2ray#114]
已在 v2ray 的配置中设置了 `"log":{"loglevel":"warning"}`  
但System Log中还是会出现如下图大量的 access log (V2Ray 4.32.1)  
<img width="757" alt="Screen Shot 2020-11-26 at 1 05 28 AM" src="https://user-images.githubusercontent.com/37198731/100259869-af1bfb80-2f83-11eb-8a90-9114946adba5.png">

**Comment by Mattraks** [comment]
[LogObject](https://www.v2fly.org/config/overview.html#logobject)

**Comment by h2fishcake** [comment]
> [LogObject](https://www.v2fly.org/config/overview.html#logobject)

没看问题内容吗？
已经设置了loglevel，但似乎影响不了system log里出现的的v2ray

**Comment by Mattraks** [comment]
> > [LogObject](https://www.v2fly.org/config/overview.html#logobject)
> 
> 没看问题内容吗？
> 已经设置了loglevel，但似乎影响不了system log里出现的的v2ray

你是没看到第一行的吗?
 "access": "none"

**Comment by h2fishcake** [comment]
可以了，感谢👍👍
