### ISSUE TITLE
kuoruan大佬可否转去xray-core？

### ISSUE THREAD

**Issue by FatDNA** [kuoruan/openwrt-v2ray#117]
vless+xtls确实要比正统的v2ray性能要好，但似乎v2fly-core不想跟进xtls了，更新也慢，v2rayNG也转xray-core了，希望kuoruan大佬也考虑转xray-core。

**Comment by kuoruan** [comment]
这个项目是做 v2ray 的，想做其他的，可以单独开个项目

**Comment by FatDNA** [comment]
期待大佬的新xray-core项目！没太多时间的话只搞custom build 也行。

**Comment by Fhokud** [comment]
https://github.com/XTLS/Xray-core/issues/209
