### ISSUE TITLE
大佬，我的是gl-inet mt1300路由器，存储只有12M，装v2ray-mini,里面选项只有vmess，没有Vless，可否加上vless，或者出一个xray for openwrt。

### ISSUE THREAD

**Issue by gossiper0305** [kuoruan/openwrt-v2ray#118]
请大佬考虑下啊，谢谢

**Comment by kuoruan** [comment]
Duplicate of #117

**Comment by gossiper0305** [comment]
看到了，期待大佬早日开启xray项目。

**Comment by kuoruan** [comment]
这里不是有吗，自己编译吧 https://github.com/xiaorouji/openwrt-passwall
我工作太忙了，最近实在没时间

**Comment by gossiper0305** [comment]
我看到了那个passwall项目了，好的，不过还是期待大佬以后可以关注xray项目，我先试试云编译passwall
