### ISSUE TITLE
求助：Out of memory: Killed process 4541 (v2ray) 

### ISSUE THREAD

**Issue by glenlau228** [kuoruan/openwrt-v2ray#126]
首先非常感谢你的帮助，昨天的问题解决了后，又出现了新的问题，能否帮我再看下是什么原因引起的，谢谢

Mon Apr 12 18:29:38 2021 daemon.info v2ray[4723]: V2Ray 4.37.2 (OpenWrt) R2 (go1.16 linux/mips)
Mon Apr 12 18:29:38 2021 daemon.info v2ray[4723]: A unified platform for anti-censorship.
Mon Apr 12 18:29:38 2021 daemon.info v2ray[4723]: 2021/04/12 10:29:38 [Info] main/jsonem: Reading config: /var/etc/v2ray/v2ray.main.json
Mon Apr 12 18:29:38 2021 authpriv.info dropbear[3327]: Exit (root) from <192.168.7.146:1297>: Exited normally
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.720081] hostapd invoked oom-killer: gfp_mask=0x100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=0
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.728264] CPU: 0 PID: 1685 Comm: hostapd Not tainted 5.4.108 #0
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.734375] Stack : 80690000 80631cf4 00000000 00000000 80630ec4 82ee3c0c 83d9ea00 8066cd03
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.742849]         805cf378 00000695 807c32d8 806914dc 00000000 00000001 82ee3bc0 b80e7898
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.751168]         00000000 00000000 807f0000 00000206 38202330 00000000 6420352e 342e3130
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.759348]         00000206 88000000 00000000 000b1cc8 80000000 82ee3d4c 83d41860 00000000
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.767629]         00000000 806914dc 00000000 00100cca 00000000 00000010 00000000 807c0000
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.776165]         ...
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.778363] Call Trace:
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.780886] [<80069864>] show_stack+0x30/0x100
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.785290] [<8012fafc>] dump_header+0x60/0x1f4
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.789770] [<80130598>] oom_kill_process+0x178/0x180
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.794801] [<80130d4c>] out_of_memory+0x220/0x348
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.799607] [<801703cc>] __alloc_pages_nodemask+0x950/0xcc8
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.805133] [<8012beb4>] pagecache_get_page+0x148/0x3f8
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.810434] [<8012c678>] filemap_fault+0x514/0x9a0
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.815262] [<8015697c>] __do_fault+0x3c/0x154
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.819573] [<8015b810>] handle_mm_fault+0x7c0/0xd00
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.824514] [<8006fe18>] do_page_fault+0x108/0x4a8
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.829271] [<8007517c>] tlb_do_page_fault_0+0x10c/0x114
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.834551] Mem-Info:
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.836882] active_anon:8286 inactive_anon:8 isolated_anon:0
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.836882]  active_file:17 inactive_file:74 isolated_file:0
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.836882]  unevictable:0 dirty:0 writeback:0 unstable:0
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.836882]  slab_reclaimable:220 slab_unreclaimable:1687
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.836882]  mapped:12 shmem:103 pagetables:97 bounce:0
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.836882]  free:2029 free_pcp:3 free_cma:0
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.868381] Node 0 active_anon:33144kB inactive_anon:32kB active_file:68kB inactive_file:296kB unevictable:0kB isolated(anon):0kB isolated(file):0kB mapped:48kB dirty:0kB writeback:0kB shmem:412kB writeback_tmp:0kB unstable:0kB all_unreclaimable? yes
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.890632] Normal free:8116kB min:8192kB low:10240kB high:12288kB active_anon:33144kB inactive_anon:32kB active_file:68kB inactive_file:296kB unevictable:0kB writepending:0kB present:65536kB managed:58304kB mlocked:0kB kernel_stack:416kB pagetables:388kB bounce:0kB free_pcp:12kB local_pcp:12kB free_cma:0kB
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.917933] lowmem_reserve[]: 0 0
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.920961] Normal: 109*4kB (UE) 35*8kB (UE) 28*16kB (UME) 14*32kB (ME) 3*64kB (ME) 3*128kB (ME) 11*256kB (UME) 2*512kB (ME) 2*1024kB (ME) 0*2048kB 0*4096kB = 8076kB
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.935798] 194 total pagecache pages
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.939353] 0 pages in swap cache
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.942649] Swap cache stats: add 0, delete 0, find 0/0
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.947966] Free swap  = 0kB
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.950687] Total swap = 0kB
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.953659] 16384 pages RAM
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.956356] 0 pages HighMem/MovableOnly
Mon Apr 12 18:29:48 2021 kern.warn kernel: [  267.960148] 1808 pages reserved
Mon Apr 12 18:29:48 2021 kern.info kernel: [  267.963276] Tasks state (memory values in pages):
Mon Apr 12 18:29:48 2021 kern.info kernel: [  267.968052] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
Mon Apr 12 18:29:48 2021 kern.info kernel: [  267.976751] [    645]    81   645      316       20    20480        0             0 ubusd
Mon Apr 12 18:29:48 2021 kern.info kernel: [  267.984874] [    646]     0   646      235        9    16384        0             0 askfirst
Mon Apr 12 18:29:48 2021 kern.info kernel: [  267.993199] [    680]     0   680      261       12    16384        0             0 urngd
Mon Apr 12 18:29:48 2021 kern.info kernel: [  268.001329] [   1003]   514  1003      316       33    20480        0             0 logd
Mon Apr 12 18:29:48 2021 kern.info kernel: [  268.009388] [   1055]     0  1055      522       42    20480        0             0 rpcd
Mon Apr 12 18:29:48 2021 kern.info kernel: [  268.017625] [   1254]     0  1254      287       12    12288        0             0 dropbear
Mon Apr 12 18:29:48 2021 kern.info kernel: [  268.026004] [   1685]     0  1685      904       40    20480        0             0 hostapd
Mon Apr 12 18:29:48 2021 kern.info kernel: [  268.034257] [   1686]     0  1686      880       26    20480        0             0 wpa_supplicant
Mon Apr 12 18:29:48 2021 kern.info kernel: [  268.043222] [   1747]     0  1747      447       47    16384        0             0 netifd
Mon Apr 12 18:29:48 2021 kern.info kernel: [  268.051438] [   1802]     0  1802      370       27    16384        0             0 odhcpd
Mon Apr 12 18:29:48 2021 kern.info kernel: [  268.059956] [   2144]     0  2144      401       30    16384        0             0 uhttpd
Mon Apr 12 18:29:48 2021 kern.info kernel: [  268.067959] [   2310]     0  2310      334       26    16384        0             0 nlbwmon
Mon Apr 12 18:29:48 2021 kern.info kernel: [  268.076343] [   2337]     0  2337      267       13    16384        0             0 odhcp6c
Mon Apr 12 18:29:48 2021 kern.info kernel: [  268.084691] [   2373]     0  2373      313       10    12288        0             0 udhcpc
Mon Apr 12 18:29:48 2021 kern.info kernel: [  268.093054] [   3125]     0  3125      314       12    16384        0             0 ntpd
Mon Apr 12 18:29:48 2021 kern.info kernel: [  268.100928] [   3375]     0  3375      302       25    16384        0             0 dropbear
Mon Apr 12 18:29:48 2021 kern.info kernel: [  268.109340] [   3472]     0  3472      315       12    20480        0             0 ash
Mon Apr 12 18:29:48 2021 kern.info kernel: [  268.117460] [   4332]   453  4332      936      248    28672        0             0 dnsmasq
Mon Apr 12 18:29:48 2021 kern.info kernel: [  268.125783] [   4723]     0  4723   170145     7543    53248        0             0 v2ray
Mon Apr 12 18:29:48 2021 kern.info kernel: [  268.133809] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),global_oom,task_memcg=/,task=v2ray,pid=4723,uid=0
Mon Apr 12 18:29:48 2021 kern.err kernel: [  268.144424] Out of memory: Killed process 4723 (v2ray) total-vm:680580kB, anon-rss:30168kB, file-rss:4kB, shmem-rss:0kB, UID:0 pgtables:52kB oom_score_adj:0
Mon Apr 12 18:29:48 2021 kern.info kernel: [  268.709612] oom_reaper: reaped process 4723 (v2ray), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
Mon Apr 12 18:29:48 2021 daemon.info procd: Instance v2ray::v2ray.main s in a crash loop 6 crashes, 16 seconds since last crash
Mon Apr 12 18:29:49 2021 daemon.notice hostapd: nl80211: nl80211_recv_beacons->nl_recvmsgs failed: -5
Mon Apr 12 18:30:05 2021 daemon.err uhttpd[2144]: luci: accepted login on / for root from 192.168.7.146

**Comment by kuoruan** [comment]
已经很清除了，内存不足
