### ISSUE TITLE
安装路径应该是 /usr/bin/v2ray/ 目录

### ISSUE THREAD

**Issue by riverscn** [kuoruan/openwrt-v2ray#13]
V2ray 官方的 Linux 安装脚本是将文件放到 /usr/bin/v2ray/ 目录下的
Openwrt 的几个 luci-app 都是以 /usr/bin/v2ray/v2ray 为路径的，一些脚本也是
目前您的 Makefile 里是将它们安装到 /usr/bin 下的，所以会和其它 luci-app 不兼容

**Comment by kuoruan** [comment]
我的 luci 支持自己填写路径，
而且放子目录就已经脱离 PATH 路径了，并不合理。
