### ISSUE TITLE
openwrt-v2ray-mini

### ISSUE THREAD

**Issue by cainiao50** [kuoruan/openwrt-v2ray#132]
路由空间不够装了mini版, 不能运行
Sat Jul 10 16:18:54 2021 daemon.info v2ray[4832]: V2Ray 4.40.1 (OpenWrt) R1 (go1.16.5 linux/mipsle)
Sat Jul 10 16:18:54 2021 daemon.info v2ray[4832]: A unified platform for anti-censorship.
Sat Jul 10 16:18:54 2021 daemon.info v2ray[4832]: 2021/07/10 08:18:54 [Info] main/jsonem: Reading config: /var/etc/v2ray/v2ray.main.json
Sat Jul 10 16:18:54 2021 daemon.info v2ray[4832]: main: failed to read config files: [/var/etc/v2ray/v2ray.main.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to load geoip: private > infra/conf/geodata/standard: failed to open file: geoip.dat > open /usr/bin/geoip.dat: no such file or directory
Sat Jul 10 16:18:54 2021 daemon.info procd: Instance v2ray::v2ray.main s in a crash loop 6 crashes, 4 seconds since last crash

**Comment by kuoruan** [comment]
删除配置里 geoip.dat 相关的内容
