### ISSUE TITLE
编译的时候提示缺少 io/fs，请问一下这个依赖应该装什么包

### ISSUE THREAD

**Issue by AshinLin** [kuoruan/openwrt-v2ray#140]
build github.com/v2fly/v2ray-core/v4/main: cannot load io/fs: malformed module path "io/fs": missing dot in first path element

![image](https://user-images.githubusercontent.com/13843885/131963492-f35347e4-27d7-49ba-9dbb-41ce679927ef.png)

**Comment by kuoruan** [comment]
看看你的 OpenWrt golang package 是哪个版本？

**Comment by AshinLin** [comment]
> 看看你的 OpenWrt golang package 是哪个版本？

实在不好意思，对这个不熟。现在只知道我用openwrt19.7的分支编译会报上面的错误，但用lede编译不会报错

**Comment by AshinLin** [comment]
> 看看你的 OpenWrt golang package 是哪个版本？

已解决，是golang版本的原因，最新版1.17没问题
