### ISSUE TITLE
V2RAY can not start after router reboot

### ISSUE THREAD

**Issue by moralrebuild** [kuoruan/openwrt-v2ray#21]
The workaround is executing '/etc/init.d/v2ray enable' manually even the V2RAY has already been enabled in Global Settings.  

Openwrt version is 18.06.4.

**Comment by kuoruan** [comment]
Is this a issue for luci-app-v2ray?

Already enabled when install luci

https://github.com/kuoruan/luci-app-v2ray/blob/master/Makefile#L35

**Comment by moralrebuild** [comment]
Yes, it's LuCI related.

**Comment by moralrebuild** [comment]
B.T.W. I saw two $ when test the variable, is it a typo?

```
if [ -z "**$$**{IPKG_INSTROOT}" ]; then
	( . /etc/uci-defaults/40_luci-v2ray ) && rm -f /etc/uci-defaults/40_luci-v2ray
	chmod 755 /etc/init.d/v2ray >/dev/null 2>&1
	/etc/init.d/v2ray enable >/dev/null 2>&1
fi
```

**Comment by kuoruan** [comment]
It's not a typo. It is used to define a shell variable in Makefile

**Comment by moralrebuild** [comment]
OK. I had ticked the 'Enabled' switch back and forth, not sure if the code can handle such common operations properly.
