### ISSUE TITLE
酷软中心显示异常

### ISSUE THREAD

**Issue by Cyloo** [kuoruan/openwrt-v2ray#22]
大神，我在网上找了一个v2ray的离线安装包，安装好了如下图（koolshare lede 版本号是 2.30）
![image](https://user-images.githubusercontent.com/18030898/65009049-edf50100-d93d-11e9-96e7-27db9affe9fc.png)

然后我在v2ray选项里选择了一键升级到最新版本，升级完成后v2ray版本号变成v4.20.0，这与你的最新版本号是对应的
![image](https://user-images.githubusercontent.com/18030898/65009099-209ef980-d93e-11e9-8244-efecaa3ffb37.png)

v2ray能**正常使用**，但是现在遇到的问题是软件**显示异常**：

1. 代理运行状态总是显示waiting
2.  自建服务器列表不显示
![image](https://user-images.githubusercontent.com/18030898/65009390-12051200-d93f-11e9-9562-b5d5fe87b455.png)

请问这个问题应该怎么解决呢

**Comment by kuoruan** [comment]
请到对应的软件作者提交issue
