### ISSUE TITLE
获取不了版本信息咋回事

### ISSUE THREAD

**Issue by hubingnan** [kuoruan/openwrt-v2ray#23]
无法获取 V2Ray 版本信息

**Comment by kuoruan** [comment]
需要具体描述

或者 在控制台运行：
```
v2ray --version
```

**Comment by hubingnan** [comment]
> 需要具体描述
> 
> 或者 在控制台运行：
> 
> ```
> v2ray --version
> ```

https://github.com/kuoruan/openwrt-v2ray/issues/23#issuecomment-532136143

**Comment by hubingnan** [comment]
![image](https://user-images.githubusercontent.com/38998449/65039456-e60c7f80-d984-11e9-860a-972e408b1923.png)

**Comment by kuoruan** [comment]
什么架构？

在命令行运行一下

```
v2ray --version
```

看看输出结果

**Comment by hubingnan** [comment]
![image](https://user-images.githubusercontent.com/38998449/65040454-03dae400-d987-11e9-87f2-6dd1e39911d7.png)
![image](https://user-images.githubusercontent.com/38998449/65040501-1c4afe80-d987-11e9-9e9d-3da2cd295b8c.png)

**Comment by kuoruan** [comment]
貌似 k2p 和 k3 都不支持，用官方的 arm 编译版本即可
