### ISSUE TITLE
stream settings 输入bug

### ISSUE THREAD

**Issue by sebastianchuk** [kuoruan/openwrt-v2ray#26]
在使用websocket+tls的情况下, 在Outbound—>Stream settings—>里面输入path: "/",然后保存。在About里面会显示出path: "反斜杠/"。我使用用的是v4.20.0-3，v2ray-core_4.20.0-3_arm_cortex-a9_vfpv3.ipk。

**Comment by kuoruan** [comment]
kuoruan/luci-app-v2ray#11
