### ISSUE TITLE
小白安装好了，配置不太懂

### ISSUE THREAD

**Issue by zjzb** [kuoruan/openwrt-v2ray#27]
你好，按照说明安装好了，但是进入界面看不懂怎么配置，之前没接触过，能否给个配置教程，在此谢过，这是我的入门之地了

**Comment by kuoruan** [comment]
抱歉，这个真没有

看懂这个你就会了

https://www.v2ray.com/chapter_02/01_overview.html

**Comment by zjzb** [comment]
谢谢，我就看这个了
