### ISSUE TITLE
我正在将其合并到openwrt

### ISSUE THREAD

**Issue by unl89** [kuoruan/openwrt-v2ray#29]
https://github.com/openwrt/packages/pull/10154

**Comment by kuoruan** [comment]
OpenWrt 对加入的包有较多的规范，而且要求在不使用 LuCI 的情况下也能使用，故需要带上 init 文件。
而我为了方便各种情况使用，将 init 文件放入的 LuCI 中，所以我并不准备主动合并入 OpenWrt，如你有需要，可以自行提交 PR。
