### ISSUE TITLE
需要在outbounds的streamSettings里面写SO_MARK吗？

### ISSUE THREAD

**Issue by sebastianchuk** [kuoruan/openwrt-v2ray#30]
"sockopt": {
"mark": 255
}

**Comment by kuoruan** [comment]
新版本的 LuCI 添加了代理路由器自身网络的选项，在启用时需要设置 iptables  mark
kuoruan/luci-app-v2ray#16

**Comment by sebastianchuk** [comment]
这个选项在哪，怎么设置呢？
