### ISSUE TITLE
装完这个和luci后在服务里找不到

### ISSUE THREAD

**Issue by poemsiu** [kuoruan/openwrt-v2ray#32]
装了你这个core 还有你的luci ipk，一共三个ipk，装完后在软件包里都显示出来了，但是服务里怎么都显示不出来。删缓存和重启都试过了，没用，求助啊！

**Comment by kuoruan** [comment]
什么系统版本？

**Comment by poemsiu** [comment]
@kuoruan 固件版本	OpenWrt R9.10.1 / LuCI Master (git-19.271.33176-b099749)
内核版本	4.19.75

**Comment by kuoruan** [comment]
```rm -rf /tmp/luci-*```

**Comment by poemsiu** [comment]
@kuoruan 执行这个命令后还是没有用

**Comment by kuoruan** [comment]
```
/usr/lib/lua/luci/controller/v2ray.lua
```
看看这个文件是否存在，内容是否和
https://github.com/kuoruan/luci-app-v2ray/blob/master/luasrc/controller/v2ray.lua
一致。

都是标准的 OpenWrt 包，不可能出现无法找到的情况，要么就是你用的非官方源码编译的固件。

**Comment by poemsiu** [comment]
@kuoruan 看了下确实没这个文件 所以是我的固件的问题吗:sweat_smile:
