### ISSUE TITLE
dns-in需要写吗

### ISSUE THREAD

**Issue by sebastianchuk** [kuoruan/openwrt-v2ray#34]
inbound和路由里面不需要dns-in吗？

**Comment by sebastianchuk** [comment]
我看你在默认配置里是路由里添加 透明代理53端口udp协议的tag对应dns-out的tag，我配置以后遇到一些奇奇怪怪的问题。在电信宽带环境下，youtube偶尔打不开。在移动宽带环境下，google和facebook打不开，google.com.hk正常打开，youtube正常打开。问题在哪里呢？

**Comment by kuoruan** [comment]
DNS 的代理一直都有点问题，我还没具体去看 kuoruan/luci-app-v2ray#7

**Comment by sebastianchuk** [comment]
我想看看iptables怎么写的，在哪能看到呢？

**Comment by kuoruan** [comment]
https://github.com/kuoruan/luci-app-v2ray/blob/7c9fec937491b6633026457cd224128a2c35aeb4/root/etc/init.d/v2ray#L270-L280

**Comment by kuoruan** [comment]
v2ray/v2ray-core#1171

**Comment by kuoruan** [comment]
刚才更新了一下 iptables

kuoruan/luci-app-v2ray@1398da118cbd70429252c8bb2c7b33e5f5b22940

试试看行不行

来自： https://xdays.me/V2RAY%E9%80%8F%E6%98%8E%E4%BB%A3%E7%90%86/
