### ISSUE TITLE
UPX压缩的一个小建议

### ISSUE THREAD

**Issue by dalton-chiou** [kuoruan/openwrt-v2ray#41]
如果启用UPX压缩的话，目前的参数是 --ultra-brute （makefile:  upx --ultra-brute $(GO_PKG_BUILD_BIN_DIR)/v2ray），比较慢。我比较了一下，压缩后的体积，使用--ultra-brute与使用--lzma只相差几K到几十K，而多耗了许多时间。
参看 https://github.com/upx/upx/issues/174 ，brute及ultra-brute多尝试的几种算法似乎意义不大。所以建议使用--lzma 。
（或者什么也不指定，就用它自己的UCL，这样最快，不过压缩出来的v2ray要大1M。）

**Comment by kuoruan** [comment]
```--ultra-brute``` 理论上是指 ```--lzma --best```，但是根据网上的反馈来看，是有一定的差别的。
如果有需要，可以提交一个 PR

**Comment by daiaji** [comment]
所以说如你用lzma算法压缩固件，那UPX也没什么卵用吧……
