### ISSUE TITLE
How to install v2ray client in OpenWrt 18.06.4

### ISSUE THREAD

**Issue by developer-sunnywu** [kuoruan/openwrt-v2ray#42]
Hello, I have 3 questions want to be answered.

1. Is it also work for  OpenWrt 18.06.4?
2. My processor is MIPS 1004Kc V2.15, which ipk should I download?
3. Is that I need to install and build afterward?

Thanks

**Comment by kuoruan** [comment]
```
opkg print-architecture
```
Get your arch. and download the right release file.
install via OPKG

**Comment by developer-sunnywu** [comment]
Hello, 

I get the following error
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for v2ray-core:
 *      ca-bundle
 * opkg_install_cmd: Cannot install package v2ray-core.

**Comment by kuoruan** [comment]
```opkg update``` then try again.
