### ISSUE TITLE
/etc/init.d/v2ray 的 typo 導致無法啟動 v2ray 服務

### ISSUE THREAD

**Issue by jasonts** [kuoruan/openwrt-v2ray#46]
機器: Xiaomi Mi Router 3G
OpenWrt 版本: 19.07.0
v2ray-core 版本: 4.22.1-3
luci-app-v2ray 版本: 1.5.2-1

情況:
在 luci 裡面無論是 reload service, 或是在 Startup 裡面 restart 都無法正常啟動
在 ssh 將生成的 json 檔案 copy 至 home directory 之後 test run 是這樣子

> root@OpenWrt:~# v2ray -test -config /root/v2ray.main.json
V2Ray 4.22.1 (OpenWrt) R3 (go1.13.5 linux/mipsle)
A unified platform for anti-censorship.
main: failed to read config file: /root/v2ray.main.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: invalid VMess user > json: cannot unmarshal string into Go struct field VMessAccount.alterId of type uint16

疑似是 /etc/init.d/v2ray 的腳本有 typo 而無法啟動，
編輯了該檔案之後恢復正常

解決方式:
vim /etc/init.d/v2ray
搜尋 `test -n "$s_vmess_client_alter_id"`
將後面的 json_add_string 改成 json_add_int
大概在 1155 行的位置

**Comment by kuoruan** [comment]
确实。
