### ISSUE TITLE
请问，是否可以推荐可用的luci ?

### ISSUE THREAD

**Issue by hqvv** [kuoruan/openwrt-v2ray#6]
谢谢大神提供op的 makefile.
我想编译进固件，但完全没接触过。能有个luci 估计会更适合我这种伸手党吧 ^^
还请大神推荐个 适用的luci的 repository

感恩

**Comment by kuoruan** [comment]
我有计划写个luci，但是最近太忙了，过一段时间开工。
Gayhub 上有一些现成的，你可以自己编译试试 https://github.com/search?q=luci-app-v2ray

**Comment by hqvv** [comment]
测试了几个 好像是那种和v2ray ss ssr集成在一起的。
期待大神的单独的v2ray的 luci了

**Comment by lllrrr** [comment]
期待大神的luci

**Comment by sparkyuanquan** [comment]
同样期待大神的LUCI 服务端。

**Comment by kuoruan** [comment]
初版大概是这个样子的，有问题请尽量提出来。https://github.com/kuoruan/luci-app-v2ray/releases/tag/v1.0.0-1
