### ISSUE TITLE
---------------

### ISSUE THREAD

**Issue by ohyeah521** [kuoruan/openwrt-v2ray#62]

**Comment by kuoruan** [comment]
涉及到透明代理模式的切换，并不能单纯的备份和还原

**Comment by ohyeah521** [comment]
> 涉及到透明代理模式的切换，并不能单纯的备份和还原

可以将代理模式状态保存到临时目录中，每次切换后判断一下模式在决定是否导入备份

**Comment by ohyeah521** [comment]
这个bug和https://github.com/kuoruan/openwrt-v2ray/issues/49#issue-555748257 这个bug其实是一个问题。

**Comment by ohyeah521** [comment]
刚刚突然想到一个新的解决方案，重启服务或修改了配置以后主动调用一个函数，该函数负责ping一下gfwlist中的域名即可，也不用备份和导入了
