### ISSUE TITLE
opkg安装方法多处报错

### ISSUE THREAD

**Issue by tonywk** [kuoruan/openwrt-v2ray#63]
Please attach the output of following commands.
路由器为K2P。
按照opkg按照步骤执行，2处报错
1:
opkg-key add kuoruan-public.key

/usr/sbin/opkg-key: line 56: usign: not found
2:
opkg update
Collected errors:
 * opkg_download: Failed to download http://openwrt.kuoruan.net/packages/releases//Packages.gz, wget returned 1.
上面可以看出releases// - 多了一个斜杠

cat /etc/*release
DISTRIB_ID="PandoraBox"
DISTRIB_CODENAME="19.02"
DISTRIB_RELEASE="19.02"
DISTRIB_VERSION="4802"
DISTRIB_REVISION="2019-02-01-git-93f2639a7"
DISTRIB_TARGET="ralink/mt7621"
DISTRIB_DESCRIPTION="PandoraBox 19.02 2019-02-01-git-93f2639a7"
DISTRIB_TAINTS="no-all busybox"
DISTRIB_MANUFACTURER="PandoraBox-Team"
DISTRIB_MANUFACTURER="http://www.pandorabox.com.cn"

opkg print-architecture
arch all 1
arch noarch 1
arch mipsel_1004kc_dsp 10

**Comment by kuoruan** [comment]
不支持潘多拉
自行添加路由器架构
