### ISSUE TITLE
v2ray无法正常使用

### ISSUE THREAD

**Issue by asdmailwl** [kuoruan/openwrt-v2ray#64]
配置完启动V2RAY
报错：
2020/04/20 04:54:00 [Warning] [3244421204] v2ray.com/core/app/dispatcher: non existing tag: direct
2020/04/20 04:54:19 [Warning] [1776006456] v2ray.com/core/app/dispatcher: non existing tag: dns_out

**Comment by kuoruan** [comment]
检查你的配置。启用 direct 和 dns_out 两个 outbound

**Comment by asdmailwl** [comment]
pve安装openwrt in86版本
防火墙 通信规则里已经打开1081端口
错误日志中时间总是于openwrt系统时间不符，我反馈这个问题时系统时间是2020年4月20日 中午12点，而错误日志中是2020年4月20日上午4点。
