### ISSUE TITLE
编译菜单选上了 Exclude geoip.dat & geosite.dat但运行提示找不到文件！

### ISSUE THREAD

**Issue by snakwu** [kuoruan/openwrt-v2ray#65]
编译菜单选上了 Exclude geoip.dat & geosite.dat，但在openwrt里运行提示找不到文件！
ps：另外选上tproxy，无法访问国外网站！

**Comment by kuoruan** [comment]
Exclude.

**Comment by snakwu** [comment]
@kuoruan  那个tproxy一选上就不能访问国外了，是什么问题？请指引
