### ISSUE TITLE
没有有效的构架

### ISSUE THREAD

**Issue by sebastianchuk** [kuoruan/openwrt-v2ray#69]
原先v2ray-core_4.23.1-1_arm_cortex-a9_vfpv3.ipk的构架现在怎么办？
改用v2ray-core_4.23.1-4_arm_cortex-a9_vfpv3-d16.ipk会提示构架不兼容。

**Comment by kuoruan** [comment]
https://openwrt.org/docs/guide-user/additional-software/opkg#change_architectures

添加一个 arch 即可
