### ISSUE TITLE
请问下ipk打包了哪些预定义域名、IP列表

### ISSUE THREAD

**Issue by ArcherCX** [kuoruan/openwrt-v2ray#7]
下午想加上geosite:category-ads-all作拦截，结果运行提示找不到

failed to parse domain rule: geosite:category-ads-all > v2ray.com/core/infra/conf: failed to load geosite: CATEGORY-ADS-ALL > v2ray.com/core/infra/conf: country not found: CATEGORY-ADS-ALL

**Comment by kuoruan** [comment]
现在的 geosite.dat 文件来自源码目录 https://github.com/v2ray/v2ray-core/tree/master/release/config
估计是太老了。
你可以从这里下载 https://github.com/v2ray/domain-list-community/releases，替换掉 ```/usr/bin/geosite.dat```

**Comment by ArcherCX** [comment]
3Q，可以了
