### ISSUE TITLE
v2ray能否支持多线程

### ISSUE THREAD

**Issue by bluebugg** [kuoruan/openwrt-v2ray#74]
Please attach the output of following commands.

大神，能让v2ray支持多线程么，路由器单线程性能实在有限，通常中低端路由器跑ws+tls模式，都在10-20mbs，如果支持多线程很多双核路由器会好很多

> 

```
cat /etc/*release
opkg print-architecture
```

**Comment by kuoruan** [comment]
不清除你说的此多线程是否是彼多线程。
Golang 本来就是支持多线程的。
如果你指的是多路复用的话，看这里 https://www.v2ray.com/chapter_02/mux.html
不是的话，请到官方仓库开 issue

**Comment by ttmi9002** [comment]
大大，是这样的，我在使用小米路由器3G上碰到这个问题，MT7621处理器运行v2ray只有单线程调用，表现为，
Chrome浏览单个youtube视频最大码率是15mps，CPU占用25%；
Chrome浏览两个youtube视频最大码率分别分12mbps和11mpbs，CPU占用50%，总码率为23mps。
证明v2ray对单个浏览只调用一个线程，无法完全发挥MT7261的处理性能。
对比斐讯N1盒子，浏览单个youtube视频最大码率能到360-400mps,CPU占用率能跑满。
在多个版本上的v2ray-core都是这样，希望能改进v2ray在MT7621的多线程调用性能。
