### ISSUE TITLE
在最新的原版openwrt19.07.2 按自述文件进行opkg在线安装后，菜单中没有v2项

### ISSUE THREAD

**Issue by cn1000** [kuoruan/openwrt-v2ray#75]

**Comment by kuoruan** [comment]
master 源码编译的吗？ 最新版的 LuCI 结构已经变了，我会在本周发布一个对19.07的测试版本

**Comment by sebastianchuk** [comment]
> master 源码编译的吗？ 最新版的 LuCI 结构已经变了，我会在本周发布一个对19.07的测试版本

我在19.07系统里面opkg install安装，构架是v2ray-core_4.23.1-5_arm_cortex-a9_vfpv3.ipk的，报错提示构架不适用，但是18.0x系统都OK。是因为现在客户端都没有支持19系统吗？

**Comment by kuoruan** [comment]
现在的客户端是支持 19 的，都是通过 19 的 sdk 编译的
但是 19 里边有写架构改名了，看看你现在的架构名字，别装错了

**Comment by sebastianchuk** [comment]
> 现在的客户端是支持 19 的，都是通过 19 的 sdk 编译的
> 但是 19 里边有写架构改名了，看看你现在的架构名字，别装错了

有改名的参考文档吗

**Comment by kuoruan** [comment]
`opkg print-architecture`
