### ISSUE TITLE
请问arm_cortex-a9_vfpv3_D16 与arm_cortex-a9_vfpv3 有什么区别？

### ISSUE THREAD

**Issue by dalton-chiou** [kuoruan/openwrt-v2ray#80]
我的路由是linksys wrt1200ac。 该下哪个，有点迷惑了。
还有，如果用opkg安装迷你版，相应命令是什么？

**Comment by kuoruan** [comment]
https://github.com/openwrt/openwrt/commit/2d61f8821c7cf99354e904139226c132554ba180
在最新的 openwrt 上改名了，你能装上哪个就用哪个

**Comment by dalton-chiou** [comment]
实测，19.07用D16；18.06用原来的（32位寄存器版？）。
后一个问题我没描述清楚。想知道的是：如果用opkg通过feeds在线安装（或upgrade）minimal版，命令是opkg install minimal.v2ray-core 吗？

**Comment by kuoruan** [comment]
feeds 上没有 minimal，正在添加

**Comment by kuoruan** [comment]
现在 feeds 上已包含 mini 版本
`opkg update && opkg install v2ray-core-mini`

**Comment by dalton-chiou** [comment]
> 现在 feeds 上已包含 mini 版本
> `opkg update && opkg install v2ray-core-mini`

刚刚试过。openwrt  18.06.8，可以正常安装。19.07.3，由于需要D16版本，无法用这个命令安装。

**Comment by kuoruan** [comment]
已经包含了 d16 版本，改一下你的 feeds 路径即可

**Comment by dalton-chiou** [comment]
谢谢。先前没注意feeds路径有变化了。
