### ISSUE TITLE
请问如何将v2ray-core升级到最新版呢

### ISSUE THREAD

**Issue by NP-Prob** [kuoruan/openwrt-v2ray#81]
前两天不是爆出来v2ray-core有一个漏洞么，然后官方紧急修复了，那么要如何升级到最新版呢？
我是通过OPKG安装的，刚查看了一下，似乎还是4.18.0版本。

**Comment by kuoruan** [comment]
已发布新版本
```
opkg update
opkg upgrade v2ray-core
```

**Comment by NP-Prob** [comment]
> 已发布新版本
> 
> ```
> opkg update
> opkg upgrade v2ray-core
> ```

感谢大佬！
不过我现在update的时候会报错，如下，是什么情况呢：
![image](https://user-images.githubusercontent.com/9911456/83383080-f97a5080-a416-11ea-886c-4b124970eaf3.png)

**Comment by kuoruan** [comment]
自己编译的固件有问题，请自行搜索解决

**Comment by NP-Prob** [comment]
> 自己编译的固件有问题，请自行搜索解决

好的，谢谢
