### ISSUE TITLE
v2ray could not start after installation

### ISSUE THREAD

**Issue by chandlersonne** [kuoruan/openwrt-v2ray#86]
Hi Xingwang,

Thanks for sharing the nice work. I tried to install your mini version of v2ray on my router that has a 16M rom and 128M memory. The installation seems successful but I couldn't get it started somehow. The command window just stuck there and there's no error message and I have to end it with a ctrl + C. I wonder if it is caused by the very limited rom/memory of my router. Have you encoutered this problem before?

**Comment by kuoruan** [comment]
Maybe you need to check your system log to see if there is any error.
