### ISSUE TITLE
Try to build for aarch64_cortex-a53 (RPi 3), but always fails. 

### ISSUE THREAD

**Issue by linanw** [kuoruan/openwrt-v2ray#9]
Having this error, not sure if any one had even successfully built for aarch64_cortex-a53 (RPi 3)?

.....
go.starlark.net/resolve
v2ray.com/core/external/github.com/lucas-clemente/quic-go/internal/congestion
v2ray.com/core/external/github.com/lucas-clemente/quic-go/internal/wire
go.starlark.net/internal/compile
v2ray.com/core/external/github.com/lucas-clemente/quic-go/internal/flowcontrol
v2ray.com/core/external/github.com/lucas-clemente/quic-go/internal/ackhandler
go.starlark.net/starlark

Cleaning module download cache (golang/go#27455)
go: finding v2ray.com/core/.go_work/build latest
go: finding v2ray.com/core/.go_work latest
can't load package: package v2ray.com/core/.go_work/build: unknown import path "v2ray.com/core/.go_work/build": cannot find module providing package v2ray.com/core/.go_work/build

make[2]: *** [/root/openwrt/build_dir/target-aarch64_cortex-a53_musl/v2ray-core-4.19.1/.built] Error 2
make[2]: Leaving directory `/root/openwrt/package/v2ray'
time: package/v2ray/compile#38.00#33.45#106.38
make[1]: *** [package/v2ray/compile] Error 2
make[1]: Leaving directory `/root/openwrt'
make: *** [package/v2ray/compile] Error 2
root@0ce88aac5df2:~/openwrt#

**Comment by kuoruan** [comment]
Did you try set proxy when build?

**Comment by linanw** [comment]
> Did you try set proxy when build?

Hi Kuoruan, thanks for the super fast response. Nope, I don't have any proxy setting, actually I didn't get what proxy do you mean? I'm with direct network to ISP in Singapore. I built the code with a docker container I built myself with Ubuntu.

**Comment by kuoruan** [comment]
From openwrt hwdata, Raspberry Pi 3 use target **brcm2708**, arm_cortex-a53_neon-vfpv4
https://openwrt.org/toh/hwdata/raspberry_pi_foundation/raspberry_pi_3_bplus
Why you build for aarch64_cortex-a53?

**Comment by linanw** [comment]
This used the SDK download from https://downloads.openwrt.org/releases/18.06.2/targets/brcm2708/bcm2710/.

aarch64_cortex-a53 is the only toolchain from it’s staging_dir/

Btw: I checked the 18.06 packages for arm_cortex-a53_neon-vfpv4, it is actually empty.

https://downloads.openwrt.org/releases/packages-18.06/arm_cortex-a53_neon-vfpv4/ (empty link)



Regards,
Bruce
________________________________

**Comment by kuoruan** [comment]
Build test passed with snapshot sdk in
https://downloads.openwrt.org/snapshots/targets/brcm2708/bcm2710/

**Comment by kuoruan** [comment]
Golang modules support added on openwrt/packages@7dc1f3e0293588ebc544e8eee104043dd0dacaf5
So you need a sdk after this date. Or update the golang package to latest
https://github.com/openwrt/packages/tree/master/lang/golang
