### ISSUE TITLE
Add new opkg key 错误 usign: not found

### ISSUE THREAD

**Issue by ztfot** [kuoruan/openwrt-v2ray#91]
Please attach the output of following commands.
openwrt运行命令时

Add new opkg key:
wget -O kuoruan-public.key http://openwrt.kuoruan.net/packages/public.key
opkg-key add kuoruan-public.key

出现
```
root@OpenWrt:~# opkg-key add kuoruan-public.key 
/usr/sbin/opkg-key: line 29: usign: not found

```

**Comment by kuoruan** [comment]
`opkg update && opkg install usign`

**Comment by shaojs321** [comment]
> `opkg update && opkg install usign`

好用
