### ISSUE TITLE
How to determine which encryption/security method does v2ray use when "security": "auto"

### ISSUE THREAD

**Issue by sgon00** [kuoruan/openwrt-v2ray#93]
Hi, I am using vmess outbound protocol. Inside the `users` object, I have `"security": "auto",` setup.
I would like to know which encryption method the v2ray will use. 
I tried to change loglevel to `"debug"` and check the log file, But there is no such information in the log file.
How can I determine which encryption method the v2ray uses?
Thanks a lot.

**Comment by kuoruan** [comment]
Please see V2Ray's document: https://www.v2ray.com/en/configuration/protocols/vmess.html#userobject

**Comment by sgon00** [comment]
@kuoruan thanks a lot for the quick reply. I did see that document before asking this question. I knew that document/spec and what should happen. But what should happen does NOT mean what will happen. I mean the implementation may NOT follow the spec. I would like to see some log info or stdout to check if v2ray openwrt client does follow the doc's rule. Are there any log that will show the encryption method name? Thanks.

**Comment by kuoruan** [comment]
Please head to V2Ray discussion to get some help: https://github.com/v2ray/discussion/issues

**Comment by sgon00** [comment]
OK, thanks.
