### ISSUE TITLE
/usr/sbin/opkg-key: line 29: usign: not found

### ISSUE THREAD

**Issue by ztfot** [kuoruan/openwrt-v2ray#94]
Please attach the output of following commands.

```
wget -O kuoruan-public.key http://openwrt.kuoruan.net/packages/public.key
opkg-key add kuoruan-public.key

```
输出为:
root@OpenWrt:~# opkg-key add kuoruan-public.key
/usr/sbin/opkg-key: line 29: usign: not found

这如何解决？

**Comment by kuoruan** [comment]
opkg update && opkg install usign
